/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lettersequences;

import java.util.HashSet;
import java.util.Set;

public class App {
    public static void main(String[] args) {
        String tiles1 = "ABCD";
        String tiles2 = "AABC";

        System.out.println(numTilePossibilities(tiles1)-numTilePossibilities(tiles2)); 
    }

    public static int numTilePossibilities(String tiles) {
        Set<String> sequences = new HashSet<>();
        backtrack(sequences, "", tiles.toCharArray(), new boolean[tiles.length()]);
        return sequences.size();
    }

    public static void backtrack(Set<String> sequences, String current, char[] tiles, boolean[] used) {
        if (!current.isEmpty()) {
            sequences.add(current);
        }

        for (int i = 0; i < tiles.length; i++) {
            if (!used[i]) {
                used[i] = true;
                backtrack(sequences, current + tiles[i], tiles, used);
                used[i] = false;
            }
        }
    }
}
